# Generated by Django 2.2.4 on 2019-08-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Published'), (1, 'Published')], default=0),
        ),
    ]
